export const UNLOCK_DATABASE_SUBMIT = 'UNLOCK_DATABASE_SUBMIT'
export const UNLOCK_DATABASE_FAILED = 'UNLOCK_DATABASE_FAILED'
export const UNLOCK_DATABASE_SUCCEEDED = 'UNLOCK_DATABASE_SUCCEEDED'
export const DATABASE_NOT_UNLOCKED = 'DATABASE_NOT_UNLOCKED'
export const DATABASE_UNLOCKED = 'DATABASE_UNLOCKED'

export const REQUEST_PASSWORD_LIST = 'REQUEST_PASSWORD_LIST'
export const RECEIVE_PASSWORD_LIST = 'RECEIVE_PASSWORD_LIST'
export const REQUEST_PASSWORD = 'REQUEST_PASSWORD'
export const RECEIVE_PASSWORD = 'RECEIVE_PASSWORD'

export const PASSWORD_COPIED_TO_CLIPBOARD = 'PASSWORD_COPIED_TO_CLIPBOARD'
export const CLIPBOARD_EMPTIED = 'CLIPBOARD_EMPTIED'
